name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${increment}"
      id: version

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Configure Docker buildx (optional)
      uses: docker/setup-buildx-action@v1  # Optional, comment out if buildx is already configured

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          delta27222/nnotes_docker:${{ steps.version.outputs.version }}
          delta27222/nnotes_docker:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
        file: ./NNotes/Dockerfile  # Update path to your Dockerfile

  